import React from 'react';
import technology from '../assets/Images/technology.jpg'
import simulationResults from '../assets/Images/simulationResults.jpg'
import lightDistribution from '../assets/Images/lightDistribution.jpg';
import defocusCurve from '../assets/Images/defocusCurve.jpg';
import curve2 from '../assets/Images/curve2.jpg';
import result1 from '../assets/Images/result1.jpg';
import result2 from '../assets/Images/result2.jpg';
import result3 from '../assets/Images/result3.jpg';
import quality from '../assets/Images/quality.jpg';




export const data = {
       
    contents:    [{key:1,head : "About Supra Phob Infocus",text : `Supraphob Infocus is a New Generation Hydrophobic Foldable IOL. Supraphob Infocus provides extended depth of focus thereby imparting the intermediate, distance and near vision with minimum incidence of Glare and Halos when compared to Multifocal IOLs.

     Supraphob Infocus IOL is made up of Hydrophobic Acrylic material with Natural Yellow Chromophore to protects from UV and other harmful radiations. Its 360° square edge design prevents PCO formation.`},

     {key:2,head:'Technology',text:`In Supraphob Infocus IOL the central small aperture refractive element gives increased depth of focus for near vision and simulate accommodation. Progressive refractive aspheric elements towards the periphery provides clear distance &amp; intermediate vision.`,image:`${technology}`},
     {key:3,head:'Simulation Results',text:`>The function of defocus showed in the MTF data is generated by Optical simulation (Snellen fraction)`,image:`${simulationResults}`},{
        key:4,head:'Light Distribution',text:`When the micron sized light rays hits smoothly on edge of the central zone, the light rays bends without any reflection, thus, eliminates scattering of light and this state of art patented technology reduces the glare for the patient.`,image:`${lightDistribution}`
     },{key:5,head:'',table:<>
     <tbody>
     <tr>
         <td><b>Pupil Size</b></td>
         <td><b>Light Energy for Near</b></td>
         <td><b>Light Energy for Distance</b></td>
         </tr>	
         <tr>
         <td>2.0mm</td>
         <td>36%</td>
         <td>64%</td>
         </tr>
         <tr>
         <td>2.5 mm</td>
         <td>22%</td>
         <td>78</td>
         </tr>
         <tr>
         <td>3.0 mm</td>
         <td>16%</td>
         <td>84%</td>
         </tr>
         <tr>
         <td>3.5 mm</td>
         <td>10%</td>
         <td>90%</td>
         </tr>
         <tr>
         <td>4.0 mm</td>
         <td>09%</td>
         <td>91%</td>
         </tr>
         <tr>
         <td>4.5 mm</td>
         <td>06%</td>
         <td>94%</td>
         </tr>
         </tbody>
     
     </>},{key:6,head:'Defocus Curve',text:`Comparison of Defocus Curve Monofocal &amp; Multifocal`,image:`${defocusCurve}`},{key:7,head:'',text:'Supraphob Infocus IOL Defocus curve proves the Extended depth of focus',image:`${curve2}`},{key:8,head:'Clinical Results',text:`Excellent functional vision, thus reduces the spectacle dependency significantly`,image:`${result1}`},{key:9,head:'',text:'Hybrid technology remarkably reduces Glare and Halos',image:`${result2}`},{key:10,head:'',text:'High level of patient satisfaction proved by International Standard Contrast sensitivity test methodology (by Mars Perceptrix chart) indicates Log CS scores of 1.48 and 1.52 Log Contrast Sensitivity under the optimal room lighting illumination (267 Lux)',image:`${result3}`},{key:11,head:'Quality & Accuracy',text:`• Each “ Supraphob Infocus ” is individually tested with Optical bench system called IOLA-MFD for power, quality and MTF for testing near and far focal points
• Higher MTF Values, higher the contrast from all distances &under all lighting conditions.`,image:`${quality}`},{key:12,head:'Salient Features',text:`• Crystal clear distance and acceptable near and intermediate vision improves the functional visual ability because of EDOF (Extended depth of Focus)
	• Unique single Zone Optic Design facilitates “ Enhanced Contrast Sensitivity ”with true Multifocality effect thus, reduces Glare and Halos`,table:<><tbody>
    <tr>
        <td>Material</td>
        <td>:</td>
        <td>Hydrophobic Acrylic Hydrophobic Yellow Chromophore</td>
        </tr>	
        <tr>
        <td>Anterior Design</td>
        <td>:</td>
        <td>Refractive EDOF</td>
        </tr>
        <tr>
        <td>Posterior Design</td>
        <td>:</td>
        <td>360° Enhanced Square Edge with Aspheric Optics</td>
        </tr>
        <tr>
        <td>Optic Size</td>
        <td>:</td>
        <td>6.00 mm</td>
        </tr>
        <tr>
        <td>Overall Size</td>
        <td>:</td>
        <td>13.00 mm</td>
        </tr>
        <tr>
        <td>Estimated A.Constant</td>
        <td>:</td>
        <td>118.8</td>
        </tr>
        <tr>
        <td>Diopter Range</td>
        <td>:</td>
        <td>+7.0 D to +30.0 D ( with 0.5 steps)</td>
        </tr>
        <tr>
        <td>Refractive Index</td>
        <td>:</td>
        <td>15.00 to 0</td>
        </tr>
        <tr>
        <td>Angulation</td>
        <td>:</td>
        <td>0°</td>
        </tr>
        <tr>
        <td>Sterilization</td>
        <td>:</td>
        <td>EO</td>
        </tr>
        </tbody></>}]
    }